version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sample_user
      - POSTGRES_DB=todosdb
    ports:
      - "5432:5432"